# Use Node base image
FROM node:20

# Set working directory
WORKDIR /app

# Copy files and install dependencies
COPY . .
RUN npm install
RUN npm run build

# Serve using Vite dev server
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]
