# Use Node base image
FROM node:20

# Set working directory
WORKDIR /app

# Copy files and install dependencies
COPY package*.json ./
RUN npm install
COPY . .

# Serve using Vite dev server
EXPOSE 5173

# Start the application
CMD ["npm", "run", "dev"]